title: Andrea Francu
# logo: /path/img.png
description: hi! this is my website
# show_downloads: true
remote_theme: codebygina/template-pintereso-bootstrap-jekyll
plugins:
  - jekyll-remote-theme
  
url: "https://andreafrancu1.github.io"
baseurl: ""      # user site = empty
